#import "../fragments/URLFragment.gql"
#import "../fragments/ImageFragment.gql"
query Performers($input: PerformerQueryInput!) {
  queryPerformers(input: $input) {
    count
    performers {
      id
      name
      disambiguation
      deleted
      aliases
      gender
      birth_date
      age
      height
      hair_color
      eye_color
      ethnicity
      country
      career_end_year
      career_start_year
      breast_type
      waist_size_us
      hip_size_us
      band_size_us
      cup_size_us
      waist_size_jp
      hip_size_jp
      band_size_jp
      cup_size_jp
      tattoos {
        location
        description
      }
      piercings {
        location
        description
      }
      urls {
        ...URLFragment
      }
      images {
        ...ImageFragment
      }
      is_favorite
    }
  }
}
